name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  release-contract:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Pool Status Admin'
      package: 'pool-status-admin'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
